---
# tasks file for server
- name: Atualiza repositorios
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: instalando pilha Lemp
  apt: name={{ item }} state=present
  become: yes
  with_items:
     -nginx
     -mysql-server
     -php-fpm
     -php-mysql
     -python-mysqldb


